root = "."
tmp_dir = "tmp"

[build]
cmd = "make bin/kleister-ui-debug"
bin = "bin/kleister-ui-debug"

args_bin = [
  "--log-pretty",
  "--log-color",
  "--log-level=debug",
  "server",
  "--server-assets=pkg/frontend/files/"
]

exclude_dir = [
  ".direnv",
  ".devenv",
  "node_modules"
]

exclude_regex = [
  "_test\\.go"
]

[misc]
clean_on_exit = true
