workspace:
  base: /srv/app
  path: src/github.com/kleister/kleister-ui

pipeline:
  testing:
    image: webhippie/nodejs:latest
    pull: true
    commands:
      - npm install
      - npm run lint
      - npm run build
      - npm run test

  server:
    image: webhippie/golang:latest
    environment:
      - GOPATH=/srv/app
    pull: true
    commands:
      - make clean
      - make deps
      - make lint
      - make generate
      - make test
      - make build

  updater:
    image: webhippie/golang:latest
    environment:
      - GOPATH=/srv/app
    pull: true
    commands:
      - make publish
    when:
      event: [ push, tag ]
      branch: [ master, refs/tags/* ]

  # coverage:
  #   image: plugins/coverage

  # rsync:
  #   image: plugins/rsync
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/release/
  #   target: /usr/share/webapps/dl/public_html/kleister-ui/master
  #   recursive: true
  #   delete: true
  #   when:
  #     event: push
  #     branch: master

  # rsync:
  #   image: plugins/rsync
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/release/
  #   target: /usr/share/webapps/dl/public_html/kleister-ui/$$TAG
  #   recursive: true
  #   delete: true
  #   when:
  #     event: tag
  #     branch: refs/tags/*

  # rsync:
  #   image: plugins/rsync
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/latest/
  #   target: /usr/share/webapps/dl/public_html/kleister-ui/latest
  #   recursive: true
  #   delete: true
  #   when:
  #     event: tag
  #     branch: refs/tags/*

  # rsync:
  #   image: plugins/rsync
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/publish/
  #   target: /usr/share/webapps/dl/public_html/kleister-ui/updates
  #   recursive: true
  #   delete: false
  #   when:
  #     event: tag
  #     branch: refs/tags/*

  # github_release:
  #   image: plugins/github-release
  #   files:
  #     - dist/release/*
  #   when:
  #     event: tag
  #     branch: refs/tags/*


  docker:
    image: plugins/docker
    storage_driver: overlay
    debug: true
    repo: kleister/kleister-ui
    tags: [ '${TAG}' ]
    when:
      event: tag
      branch: refs/tags/*

  docker:
    image: plugins/docker
    storage_driver: overlay
    debug: true
    repo: kleister/kleister-ui
    tags: [ 'latest' ]
    when:
      event: push
      branch: master

  # gitter:
  #   image: plugins/gitter
