workspace:
  base: /srv/app
  path: src/github.com/kleister/kleister-ui

branches:
  - master

pipeline:
  cache-restore:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    restore: true
    when:
      local: false

  frontend-prepare:
    image: webhippie/nodejs:latest
    pull: true
    commands:
      - yarn install --frozen-lockfile

  frontend-lint:
    image: webhippie/nodejs:latest
    pull: true
    group: frontend
    commands:
      - yarn run lint

  frontend-test:
    image: webhippie/nodejs:latest
    pull: true
    group: frontend
    commands:
      - yarn run test

  frontend-build:
    image: webhippie/nodejs:latest
    pull: true
    group: frontend
    commands:
      - yarn run build

  backend-prepare:
    image: webhippie/golang:edge
    pull: true
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make clean
      - make retool
      - make generate

  backend-vet:
    image: webhippie/golang:edge
    pull: true
    group: backend
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make vet

  backend-check:
    image: webhippie/golang:edge
    pull: true
    group: backend
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make megacheck

  backend-lint:
    image: webhippie/golang:edge
    pull: true
    group: backend
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make lint

  backend-test:
    image: webhippie/golang:edge
    pull: true
    group: backend
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make test

  backend-build:
    image: webhippie/golang:edge
    pull: true
    group: backend
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make build

  backend-windows:
    image: karalabe/xgo-latest:latest
    pull: true
    group: release
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make release-dirs release-windows
    when:
      event: [ push, tag ]
      branch: [ master, release/* ]

  backend-linux:
    image: karalabe/xgo-latest:latest
    pull: true
    group: release
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make release-dirs release-linux
    when:
      event: [ push, tag ]
      branch: [ master, release/* ]

  backend-darwin:
    image: karalabe/xgo-latest:latest
    pull: true
    group: release
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make release-dirs release-darwin
    when:
      event: [ push, tag ]
      branch: [ master, release/* ]

  backend-finish:
    image: webhippie/golang:edge
    pull: true
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make release-copy release-check
    when:
      event: [ push, tag ]
      branch: [ master, release/* ]

  docker-amd64:
    image: plugins/docker:17.05
    pull: true
    group: docker
    secrets: [ docker_username, docker_password ]
    repo: kleister/kleister-ui
    auto_tag: true
    when:
      event: [push, tag]
      branch: master

  docker-i386:
    image: plugins/docker:17.05
    pull: true
    group: docker
    secrets: [ docker_username, docker_password ]
    repo: kleister/kleister-ui
    dockerfile: Dockerfile.i386
    auto_tag: true
    auto_tag_suffix: i386
    when:
      event: [push, tag]
      branch: master

  docker-arm:
    image: plugins/docker:17.05
    pull: true
    group: docker
    secrets: [ docker_username, docker_password ]
    repo: kleister/kleister-ui
    dockerfile: Dockerfile.arm
    auto_tag: true
    auto_tag_suffix: arm
    when:
      event: [push, tag]
      branch: master

  docker-arm64:
    image: plugins/docker:17.05
    pull: true
    group: docker
    secrets: [ docker_username, docker_password ]
    repo: kleister/kleister-ui
    dockerfile: Dockerfile.arm64
    auto_tag: true
    auto_tag_suffix: arm64
    when:
      event: [push, tag]
      branch: master

  docker-microbadger:
    image: plugins/webhook:1
    pull: true
    secrets:
      - source: microbadger_token
        target: plugin_urls
    when:
      event: [ push, tag ]
      branch: [ master ]

  cache-rebuild:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    rebuild: true
    mount:
      - _tools/bin
      - _tools/pkg
      - node_modules
    when:
      local: false
      event: [ push ]
      branch: [ master ]

  cache-flush:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    flush: true
    flush_age: 14
    when:
      local: false
      event: [ push ]
      branch: [ master ]

  archive-release:
    image: plugins/s3:1
    pull: true
    secrets: [ s3_endpoint, aws_access_key_id, aws_secret_access_key, s3_bucket ]
    source: dist/release/*
    target: /kleister/ui/master
    strip_prefix: dist/release/
    path_style: true
    when:
      event: [ push ]
      branch: [ master ]

  archive-release:
    image: plugins/s3:1
    pull: true
    secrets: [ s3_endpoint, aws_access_key_id, aws_secret_access_key, s3_bucket ]
    source: dist/release/*
    target: /kleister/ui/${DRONE_TAG##v}
    strip_prefix: dist/release/
    path_style: true
    when:
      event: [ tag ]
      branch: [ master ]

  github-release:
    image: plugins/github-release:1
    pull: true
    secrets: [ github_token ]
    files:
      - dist/release/*
    when:
      event: [ tag ]
      branch: [ master ]

  notify-gitter:
    image: plugins/gitter:1
    pull: true
    secrets: [ gitter_webhook ]
    when:
      local: false
      status: [ success, failure ]
