build:
  test:
    image: webhippie/nodejs:latest
    commands: []

publish:
  coverage:
    server: http://coverage.dronehippie.de
    token: $$GITHUB_APIKEY
    when:
      branch: master

  github_release:
    api_key: $$GITHUB_APIKEY
    files:
      - dist/release/*
    when:
      event: tag

notify:
  gitter:
    webhook:
      - $$GITTER_WEBHOOK
    when:
      repo: solderapp/solder-ui

cache:
  mount:
    - node_modules
