# escape=`
FROM microsoft/nanoserver:10.0.14393.1593

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" `
  org.label-schema.name="Kleister UI" `
  org.label-schema.vendor="Thomas Boerger" `
  org.label-schema.schema-version="1.0"

EXPOSE 9000 80 443
VOLUME ["\\kleister"]

ENV KLEISTER_UI_ASSETS /assets
ENV KLEISTER_UI_STORAGE /kleister

ENTRYPOINT ["\\kleister-ui.exe"]
CMD ["server"]

COPY dist/static /assets
COPY kleister-ui.exe kleister-ui.exe
