FROM arm32v6/alpine:3.19
RUN apk add --no-cache ca-certificates mailcap

EXPOSE 8000 8080
ENTRYPOINT ["/usr/bin/kleister-ui"]
CMD ["server"]

ENV KLEISTER_UI_ASSETS /usr/share/kleister

COPY static /usr/share/kleister
COPY bin/kleister-ui /usr/bin/kleister-ui
