FROM arm32v6/alpine:3.21

RUN apk add --no-cache ca-certificates mailcap && \
    addgroup -g 1337 kleister && \
    adduser -D -u 1337 -h /var/lib/kleister -G kleister kleister

EXPOSE 8001 8081
ENTRYPOINT ["/usr/bin/kleister-ui"]
CMD ["server"]

COPY --chown=1337:1337 static /usr/share/kleister
COPY bin/kleister-ui /usr/bin/kleister-ui
WORKDIR /var/lib/kleister
USER kleister
