# escape=`
FROM microsoft/nanoserver:10.0.14393.2430

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" `
  org.label-schema.name="Kleister UI" `
  org.label-schema.vendor="Thomas Boerger" `
  org.label-schema.schema-version="1.0"

EXPOSE 9000 9010

ENV KLEISTER_UI_ASSETS c:\assets

ENTRYPOINT ["c:\\kleister-ui.exe"]
CMD ["server"]

COPY dist/static c:\assets
COPY bin/kleister-ui.exe c:\kleister-ui.exe
