FROM arm64v8/alpine:3.15
RUN apk add --no-cache ca-certificates mailcap

EXPOSE 8000 8080
ENTRYPOINT ["/usr/bin/kleister-ui"]
CMD ["server"]

ENV KLEISTER_UI_ASSETS /usr/share/kleister

COPY dist/static /usr/share/kleister
COPY dist/binaries/kleister-ui /usr/bin/kleister-ui
